
// Objective-C API for talking to the following Go packages
//
//	gitlab.udux.com/tools/rntools
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Rntools_FRAMEWORK_H__
#define __Rntools_FRAMEWORK_H__

#include "Rntools.objc.h"
#include "Universe.objc.h"

#endif
